### ISSUE TITLE
Problems after update to latest version of Tablesorter 2.25

### ISSUE THREAD

**Issue by fcferreira29** [Mottie/tablesorter#1140] opened 2016-01-25 12:12 UTC
Hello Mottie,

i am having a problem with tablesorter,

in the previous version of the Tablesorter, 2.23.3, the grouping was working fine,

i had that problem when changing tabs on the same page, to have 2 instances of the tablesorter, and i did a workaround to fix it, did a call on the page with javascript to call the inicialize the tablesorter when i change the tab,

the problem is that with the new version of tablesorter 2.25.3 the widget was updated too, with 2.24.4 and now when i change tabs i have this error

TypeError: e.rowData is undefined (line 208)

there is no problem with the first tab, this happens when i change tabs and have to call a new instance of tablesorter,

Best Regards,

Fábio Ferreira

**Comment by Mottie** [comment] 2016-01-25 13:45
Hi @fcferreira29!

Are you saying that error is in the grouping widget? I tried the [main demo](http://mottie.github.io/tablesorter/docs/example-widget-grouping.html) and did not see the error you mention. Would you please modify [this demo](http://jsfiddle.net/Mottie/4ac5kr3o/) to show me the error, so that it would make it easier for me to troubleshoot the problem? Thanks!

**Comment by fcferreira29** [comment] 2016-01-25 14:39
try having 2 diferent tablesorters (two lists) on the same page, the first is "active" the second is activated by a button, when you click the button you have that error (that was what fired the error), we have created a function of the tablesorter, so this way we can call it by javascript initTableSorter = function (id) {    if (id == undefined) {
        id = '';
    }
    
    // call the tablesorter plugin and apply the uitheme widget
    $('.tablesorter' + id).tablesorter({
 in the page, you put a second button that calls a new instance of the tablesorter, that was the way we found the error we did this because when you have two tablesorters on the same page, and in different tabs the second tablesorter is not "rendered" so to correct that we call call initTableSorter(2) for example, to create an instance for the new list, when we click the tab we call that. Thanks, FF Date: Mon, 25 Jan 2016 05:45:26 -0800From: notifications@github.comTo: tablesorter@noreply.github.comCC: fcferreira@msn.comSubject: Re: [tablesorter] Problems after update to latest version of Tablesorter 2.25 (#1140)Hi @fcferreira29!

Are you saying that error is in the grouping widget? I tried the main demo and did not see the error you mention. Would you please modify this demo to show me the error, so that it would make it easier for me to troubleshoot the problem? Thanks!

**Comment by Mottie** [comment] 2016-01-25 16:49
Please see [this demo](http://jsfiddle.net/Mottie/abkNM/786/) on how to use tablesorter inside of jQuery UI tabs.

Basically, that code initializes the table when the tab is opened. All subsequent times the tab is opened, the widgets get reapplied.

**Comment by Mottie** [comment] 2016-01-25 16:50
Oh, we went through this before in #1014... what changed?

**Comment by Mottie** [comment] 2016-01-25 16:57
Here, try [this demo](http://jsfiddle.net/Mottie/abkNM/7595/).

**Comment by fcferreira29** [comment] 2016-01-25 17:02
on the example you sent you havent a group selected by default, on our case is trigged by the changing of the Tab because of the order of the list, we solved the other problem by doing a new instance of the tablesorter, but to this case it does not work because of the error i told you about. Date: Mon, 25 Jan 2016 08:57:20 -0800From: notifications@github.comTo: tablesorter@noreply.github.comCC: fcferreira@msn.comSubject: Re: [tablesorter] Problems after update to latest version of Tablesorter 2.25 (#1140)Here, try this demo.

**Comment by Mottie** [comment] 2016-01-25 17:08
That's what I'm saying, the demo I just shared does not have an error, so please share the code you are using as the issue is probably there.

**Comment by fcferreira29** [comment] 2016-01-25 17:35
i fixed the problem by doing this $('.tablesorter3').trigger('update'); this way when the tab is clicked i do update and put the grouping :D thanks for your help,  FF Date: Mon, 25 Jan 2016 09:09:03 -0800From: notifications@github.comTo: tablesorter@noreply.github.comCC: fcferreira@msn.comSubject: Re: [tablesorter] Problems after update to latest version of Tablesorter 2.25 (#1140)That's what I'm saying, the demo I just shared does not have an error, so please share the code you are using as the issue is probably there.

**Comment by Mottie** [comment] 2016-01-25 18:37
So no more error?

**Comment by fcferreira29** [comment] 2016-01-25 18:40
yes, with the fix i did the error is gone :D

Date: Mon, 25 Jan 2016 10:37:50 -0800

**Comment by Mottie** [comment] 2016-02-15 20:13
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Closed by Mottie** 2016-02-15 20:13 UTC
Labels: Demo, How To..., Widget, Widget-Group
