### ISSUE TITLE
Column with number and multiple . not getting sorted

### ISSUE THREAD

**Issue by virendrachandak** [Mottie/tablesorter#880] opened 2015-04-21 23:23 UTC
Columns with numbers and multiple . are not getting sorted.

e.g. column
```
5.5.21
5.5.23
5.5.21
5.5.21
5.5.23
5.5.23
```

When sorted we get the following output:
```
5.5.21
5.5.21
5.5.23
5.5.21
5.5.23
5.5.23
```
or
```
5.5.23
5.5.23
5.5.21
5.5.23
5.5.21
5.5.21
```

**Comment by Mottie** [comment] 2015-04-22 00:01
Hi @virendrachandak!

The problem is that I moved the "ipAddress" parser out from the core and into the ["parser-network.js" file](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-network.js).

Yes, I know that isn't an ip address, but if the same number of sections (separated by periods) is used throughout the column, there shouldn't be a problem with using the ip address parser.

In [this demo](http://jsfiddle.net/856bzzeL/154/), the "parser-network" file is loaded and in the header cell a class name of "sorter-ipv4Address" was included to get the sorting to work properly.

```html
<th class="sorter-ipv4Address">Value</th>
```

```js
$(function () {
    $('table').tablesorter({
		theme: 'blue'
	});
});
```

**Comment by Mottie** [comment] 2015-04-22 00:10
@TheSin- told me that I should also mention that there is also a semver validator/sorter available ([demo](http://mottie.github.io/tablesorter/docs/example-option-textsorter-semver.html)). The ["semver-mod.js" file](https://github.com/Mottie/tablesorter/blob/master/js/extras/semver-mod.js) is not really a parser, it's a different sorter available in the extras folder.

**Comment by Mottie** [comment] 2015-05-17 20:47
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.

**Closed by Mottie** 2015-05-17 20:47 UTC
Labels: Demo, Extras, How To..., Parser
