### ISSUE TITLE
jquery.tablesorter.widget.js

### ISSUE THREAD

**Issue by SPlatten** [Mottie/tablesorter#924] opened 2015-06-01 14:40 UTC
Sorry if this is in the wrong place, the last thread was closed. 

I used this as a reference: http://jsfiddle.net/1a5yu8yq/21/

I've downloaded the scripts and css files and have been developing using Firebug, I get an error on line 1893, as far as I can tell the result from .val( setFilters[ i ] ) isn't valid and doesn't have the function .trigger()

**Comment by TheSin-** [comment] 2015-06-01 14:51
you need to use the version from git, not the jsfiddle, that one is old.

**Comment by Mottie** [comment] 2015-06-01 15:36
Modify that demo & show me the error; it should have been fixed in #920, but I was never able to reproduce the error.

Next time, if the issue is related to some thing that was previously open, please respond in that thread, *even if it is closed*. Sometimes an issue is closed by the commit.

**Comment by SPlatten** [comment] 2015-06-01 19:59
Sorry, I'm not sure how to upload / replace resources in JsFiddle.

**Comment by Mottie** [comment] 2015-06-01 20:54
Actually, that demo is using the scroller widget code from the master branch.

If you want to change scripts in jsFiddle, add a URL to the "External Resources" section on the left... it will not allow you to add the same file twice (if you want to re-order files), so you might need to delete a resource before re-adding it back.

What I really need is to see this error to make it easier to troubleshoot. The `$column` variable on line 1893 of the jquery.tablesorter.widgets.js file should have an element since there are multiple checks before that line ensuring there is an element. So, add the options you are using, not the complete list of options provided in issue #920 - just the ones that are different. And the HTML being used.

**Comment by SPlatten** [comment] 2015-06-02 07:14
I'm doing something wrong here...

I click on External Resources, add the file name, but how do I upload the
content of the file?  I don't see any upload options.

I'm absolutely positive that I have done this before, but can't see why I
can't do it now.

On 1 June 2015 at 21:54, Rob G <notifications@github.com> wrote:

> Actually, that demo is using the scroller widget code from the master
> branch.
>
> If you want to change scripts in jsFiddle, add a URL to the "External
> Resources" section on the left... it will not allow you to add the same
> file twice (if you want to re-order files), so you might need to delete a
> resource before re-adding it back.
>
> What I really need is to see this error to make it easier to troubleshoot.
> The $column variable on line 1893 of the jquery.tablesorter.widgets.js
> file should have an element since there are multiple checks before that
> line ensuring there is an element. So, add the options you are using, not
> the complete list of options provided in issue #920
> <https://github.com/Mottie/tablesorter/issues/920> - just the ones that
> are different. And the HTML being used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mottie/tablesorter/issues/924#issuecomment-107706028>.
>



-- 
 <http://about.me/SPlatten>
[image: Simon Platten on about.me]

Simon Platten
about.me/SPlatten
    <http://about.me/SPlatten>

**Comment by SPlatten** [comment] 2015-06-02 08:43
Below is a demo that illutrates one of the issues I'm facing, if there are
less than a 10 items in the table, the headers do no work correctly, the
bottom header is in the wrong place.

<!DOCTYPE html>
<html>
<head>
 <meta charset="utf-8">
    <title>jQuery plugin: Tablesorter 2.0 - Scroller Widget</title>
    
    <link rel="stylesheet" type="text/css"
href="/jquery/jquery-ui.min.css"/>
    <link rel="stylesheet" type="text/css"
href="/jquery/styles/tablesorter/theme.blue.css"/>
  <link rel="stylesheet" type="text/css"
href="/jquery/styles/tablesorter/jquery.tablesorter.pager.css"/>
    
  <script src="/jquery/scripts/jquery-2.0.2.min.js"></script>

    
  <script type='text/javascript' src="/jquery/jquery-ui.js"></script>
    <script type='text/javascript'
src="/jquery/scripts/tablesorter/jquery.tablesorter.combined.js"></script>
  <script type='text/javascript'
src="/jquery/scripts/tablesorter/jquery.tablesorter.pager.js"></script>
    <script type='text/javascript'
src="/jquery/scripts/tablesorter/widgets/widget-scroller.js"></script>
    <script id="js">
  $(function(){
    $('#tk_tblrpt').tablesorter({
        theme: 'blue',
        headerTemplate: '{content}',
        widgets: ['zebra', 'filter', 'scroller'],
        widgetOptions: {
            scroller_height: 400,
            scroller_fixedColumns: 2,
            scroller_rowHighlight: 'hover'
        }
    })
    .tablesorterPager({
        container: $('.pager'),
        output: '{startRow:input} to {endRow} ({totalRows})',
        updateArrows: true,
        page: 0,
        size: 10,
        savePages: true,
        storageKey: 'tablesorter-pager',
        fixedHeight: true,
        removeRows: false
    });
});
  </script>
    <style type='text/css' id='css'>/* OPTIONAL CSS! */
#tk_tblrpt tbody td {
    /* force "Notes" column to not wrap, so we get a horizontal scrolling
demo! */
    white-space: nowrap;
    /* Add min column width, or "Index" column filter gets too narrow to
use */
    min-width: 60px;
}
*, *:before, *:after {
  box-sizing: inherit;
}
/* Extra selectors needed to override the default styling */
table.tablesorter tbody tr.normal-row td {
  background-color: #F2CFAE;
  color: #fff;
}
table.tablesorter tbody tr.alt-row td {
  background-color: #F78E1E;
  color: #fff;
}
#tk_tblrpt tbody td {
    white-space: nowrap;
    min-width: 32px;
}
th.rotate > div {
  transform: translate(8px, -6px) rotate(300deg);
  white-space: nowrap;
  padding: 0 0 0 0;
  margin: 0 0 0 0;
  height: 72px;
}
/* pager wrapper, div */
.tablesorter-pager {
  padding: 5px;
}
/* pager wrapper, in thead/tfoot */
td.tablesorter-pager {
  background-color: #e6eeee;
  margin: 0; /* needed for bootstrap .pager gets a 18px bottom margin */
}
/* pager navigation arrows */
.tablesorter-pager img {
  vertical-align: middle;
  margin-right: 2px;
  cursor: pointer;
}
/* pager output text */
.tablesorter-pager .pagedisplay {
  padding: 0 5px 0 5px;
  width: 50px;
  text-align: center;
}
/* pager element reset (needed for bootstrap) */
.tablesorter-pager select {
  margin: 0;
  padding: 0;
}
/*** css used when "updateArrows" option is true ***/
/* the pager itself gets a disabled class when the number of rows is less
than the size */
.tablesorter-pager.disabled {
  display: none;
}
/* hide or fade out pager arrows when the first or last row is visible */
.tablesorter-pager .disabled {
  /* visibility: hidden */
  opacity: 0.5;
  filter: alpha(opacity=50);
  cursor: default;
}
  </style>
  </head>
  <body>
    <div id="main">
      <table id="tk_tblrpt">
       <thead>
               <tr>
            <th>Name</th>
            <th>Company</th>
            <th>Cluster(s)</th>
            <th>Group(s)</th>
            <th>Basic<br />Hours</th>
            <th class='rotate'
                style='width:40px;'><div><span>*2015-05-02</span></div></th>
            <th class='rotate'
                style='width:40px;'><div><span>2015-05-01</span></div></th>
            <th class='rotate'
                style='width:40px;background-color: #f18e00;color:#000000'>
              <div><span>2015-05-31</span></div>
            </th>
            <th class='rotate'
                style='width:40px;background-color: #f18e00;color:#000000'>
              <div><span>2015-05-30</span></div>
            </th>
          </tr>
            </thead>
            <tfoot>
               <tr>
            <th>Name</th>
            <th>Company</th>
            <th>Cluster(s)</th>
            <th>Group(s)</th>
            <th>Basic<br />Hours</th>
            <th class='rotate'
                style='width:40px;'><div><span>*2015-05-02</span></div></th>
            <th class='rotate'
                style='width:40px;'><div><span>2015-05-01</span></div></th>
            <th class='rotate'
                style='width:40px;background-color: #f18e00;color:#000000'>
              <div><span>2015-05-31</span></div>
            </th>
            <th class='rotate'
                style='width:40px;background-color: #f18e00;color:#000000'>
              <div><span>2015-05-30</span></div>
            </th>
          </tr>
            </tfoot>
          <tbody>
            <tr>
              <td>Simon Platten</td>
              <td>RRC Controls Services</td>
              <td>Engineering</td>
              <td>RRC-Support</td>
              <td align='right'>40:00</td>
              <td align='right'>02:15</td>
              <td align='right'>08:55</td>
              <td align='right'>00:00</td>
              <td align='right'>00:00</td>
            </tr>
              </tbody>
         </table>
    </div>
    
    <div id="pager" class="pager">
      <form>
        <img src="/images/first.png" class="first"/>
        <img src="/images/prev.png" class="prev"/>
        <span class="pagedisplay"></span> 
        <img src="/images/next.png" class="next"/>
        <img src="/images/last.png" class="last"/>
        <select class="pagesize">
          <option value="10">10</option>
          <option value="20">20</option>
          <option value="30">30</option>
          <option value="40">40</option>
        </select>
      </form>
    </div>
  </body>
</html>


On 2 June 2015 at 08:13, Simon Platten <simonaplatten@gmail.com> wrote:

> I'm doing something wrong here...
>
> I click on External Resources, add the file name, but how do I upload the
> content of the file?  I don't see any upload options.
>
> I'm absolutely positive that I have done this before, but can't see why I
> can't do it now.
>
> On 1 June 2015 at 21:54, Rob G <notifications@github.com> wrote:
>
>> Actually, that demo is using the scroller widget code from the master
>> branch.
>>
>> If you want to change scripts in jsFiddle, add a URL to the "External
>> Resources" section on the left... it will not allow you to add the same
>> file twice (if you want to re-order files), so you might need to delete a
>> resource before re-adding it back.
>>
>> What I really need is to see this error to make it easier to
>> troubleshoot. The $column variable on line 1893 of the
>> jquery.tablesorter.widgets.js file should have an element since there are
>> multiple checks before that line ensuring there is an element. So, add the
>> options you are using, not the complete list of options provided in issue
>> #920 <https://github.com/Mottie/tablesorter/issues/920> - just the ones
>> that are different. And the HTML being used.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Mottie/tablesorter/issues/924#issuecomment-107706028>
>> .
>>
>
>
>
> --
>  <http://about.me/SPlatten>
> [image: Simon Platten on about.me]
>
> Simon Platten
> about.me/SPlatten
>     <http://about.me/SPlatten>
>



-- 
 <http://about.me/SPlatten>
[image: Simon Platten on about.me]

Simon Platten
about.me/SPlatten
    <http://about.me/SPlatten>

**Comment by SPlatten** [comment] 2015-06-02 13:59
I've been trying to resolve some of the issues and making some progress.  The page I posted above has different issues to the ones I'm experiencing on the live build.

The live environment builds the table content from a socket feed, jquery.tablesorter.combined.js was erroring on line 4068, it turns out that the array setFilters was 0 length and was trying to reference the 0 element.

I added:

            if ( setFilters.length ) {
              var objFilter = setFilters[ i ];
              
              if ( objFilter != undefined ) { 
						    $column.val( objFilter ).trigger( 'change.tsfilter' );
              }
            }

This resolved the error and the pager now renders correctly.  However now, with just 1 item in the table, the headers do not line up with the columns.

**Comment by Mottie** [comment] 2015-06-02 14:56
Yeah, I noticed that the fixed column footer gets pushed down when a table has less than 10 or so rows. This appears to be a problem introduced in some recent updates.

I still don't know why that line is causing an error, but from your code it's due to an undefined value... hmmm.

**Comment by TheSin-** [comment] 2015-06-02 14:59
is there an example of the issue with 10 or less rows?  I'm sure I tested this it's why I added 5 as an option to the pager during our tests :\

**Comment by Mottie** [comment] 2015-06-02 15:05
http://jsfiddle.net/1a5yu8yq/28/

**Comment by SPlatten** [comment] 2015-06-02 15:05
The HTML I posted will show it, with only 1 row in the table.

On 2 June 2015 at 15:59, Justin F. Hallett <notifications@github.com> wrote:

> is there an example of the issue with 10 or less rows? I'm sure I tested
> this it's why I added 5 as an option to the pager during our tests :\
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mottie/tablesorter/issues/924#issuecomment-107983989>.
>



-- 
 <http://about.me/SPlatten>
[image: Simon Platten on about.me]

Simon Platten
about.me/SPlatten
    <http://about.me/SPlatten>

**Comment by SPlatten** [comment] 2015-06-02 15:06
Yep, notice how the fixed column footer headers are screwed up.

2015-06-02 16:05 GMT+01:00 Rob G <notifications@github.com>:

> http://jsfiddle.net/1a5yu8yq/28/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mottie/tablesorter/issues/924#issuecomment-107985329>.
>



-- 
 <http://about.me/SPlatten>
[image: Simon Platten on about.me]

Simon Platten
about.me/SPlatten
    <http://about.me/SPlatten>

**Comment by TheSin-** [comment] 2015-06-02 15:06
that's lots of work to copy and sort through that paste, hence why I asked for demo ;)  Thanks Mottie I'll look into this issue.

**Comment by SPlatten** [comment] 2015-06-02 15:10
Not sure if this thread is in sync with github, but I posted more
information on github.

On 2 June 2015 at 16:06, Justin F. Hallett <notifications@github.com> wrote:

> that's lots of work to copy and sort through that paste, hence why I asked
> for demo ;) Thanks Mottie I'll look into this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mottie/tablesorter/issues/924#issuecomment-107985645>.
>



-- 
 <http://about.me/SPlatten>
[image: Simon Platten on about.me]

Simon Platten
about.me/SPlatten
    <http://about.me/SPlatten>

**Comment by SPlatten** [comment] 2015-06-02 15:17
I discovered what the break between the fixed columns and the scrollable
columns is....Around my div container, I had <center></center>  tags,
removing these removes the gap.  However there is still a difference
between the data row and the header row total lengths and no footer header
row.

On 2 June 2015 at 16:10, Simon Platten <simonaplatten@gmail.com> wrote:

> Not sure if this thread is in sync with github, but I posted more
> information on github.
>
> On 2 June 2015 at 16:06, Justin F. Hallett <notifications@github.com>
> wrote:
>
>> that's lots of work to copy and sort through that paste, hence why I
>> asked for demo ;) Thanks Mottie I'll look into this issue.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Mottie/tablesorter/issues/924#issuecomment-107985645>
>> .
>>
>
>
>
> --
>  <http://about.me/SPlatten>
> [image: Simon Platten on about.me]
>
> Simon Platten
> about.me/SPlatten
>     <http://about.me/SPlatten>
>



-- 
 <http://about.me/SPlatten>
[image: Simon Platten on about.me]

Simon Platten
about.me/SPlatten
    <http://about.me/SPlatten>

**Comment by SPlatten** [comment] 2015-06-02 15:20
Another possible, in my datarows, I have <br /> between multiple data
items, these seem to screw up the column widths.

On 2 June 2015 at 16:17, Simon Platten <simonaplatten@gmail.com> wrote:

> I discovered what the break between the fixed columns and the scrollable
> columns is....Around my div container, I had <center></center>  tags,
> removing these removes the gap.  However there is still a difference
> between the data row and the header row total lengths and no footer header
> row.
>
> On 2 June 2015 at 16:10, Simon Platten <simonaplatten@gmail.com> wrote:
>
>> Not sure if this thread is in sync with github, but I posted more
>> information on github.
>>
>> On 2 June 2015 at 16:06, Justin F. Hallett <notifications@github.com>
>> wrote:
>>
>>> that's lots of work to copy and sort through that paste, hence why I
>>> asked for demo ;) Thanks Mottie I'll look into this issue.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/Mottie/tablesorter/issues/924#issuecomment-107985645>
>>> .
>>>
>>
>>
>>
>> --
>>  <http://about.me/SPlatten>
>> [image: Simon Platten on about.me]
>>
>> Simon Platten
>> about.me/SPlatten
>>     <http://about.me/SPlatten>
>>
>
>
>
> --
>  <http://about.me/SPlatten>
> [image: Simon Platten on about.me]
>
> Simon Platten
> about.me/SPlatten
>     <http://about.me/SPlatten>
>



-- 
 <http://about.me/SPlatten>
[image: Simon Platten on about.me]

Simon Platten
about.me/SPlatten
    <http://about.me/SPlatten>

**Comment by SPlatten** [comment] 2015-06-02 15:27
I'm puzzled, this all seems ok:

http://jsfiddle.net/SimonPlatten/1a5yu8yq/38/

Apart from the headings on the footer.


On 2 June 2015 at 16:20, Simon Platten <simonaplatten@gmail.com> wrote:

> Another possible, in my datarows, I have <br /> between multiple data
> items, these seem to screw up the column widths.
>
> On 2 June 2015 at 16:17, Simon Platten <simonaplatten@gmail.com> wrote:
>
>> I discovered what the break between the fixed columns and the scrollable
>> columns is....Around my div container, I had <center></center>  tags,
>> removing these removes the gap.  However there is still a difference
>> between the data row and the header row total lengths and no footer header
>> row.
>>
>> On 2 June 2015 at 16:10, Simon Platten <simonaplatten@gmail.com> wrote:
>>
>>> Not sure if this thread is in sync with github, but I posted more
>>> information on github.
>>>
>>> On 2 June 2015 at 16:06, Justin F. Hallett <notifications@github.com>
>>> wrote:
>>>
>>>> that's lots of work to copy and sort through that paste, hence why I
>>>> asked for demo ;) Thanks Mottie I'll look into this issue.
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/Mottie/tablesorter/issues/924#issuecomment-107985645>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>>  <http://about.me/SPlatten>
>>> [image: Simon Platten on about.me]
>>>
>>> Simon Platten
>>> about.me/SPlatten
>>>     <http://about.me/SPlatten>
>>>
>>
>>
>>
>> --
>>  <http://about.me/SPlatten>
>> [image: Simon Platten on about.me]
>>
>> Simon Platten
>> about.me/SPlatten
>>     <http://about.me/SPlatten>
>>
>
>
>
> --
>  <http://about.me/SPlatten>
> [image: Simon Platten on about.me]
>
> Simon Platten
> about.me/SPlatten
>     <http://about.me/SPlatten>
>



-- 
 <http://about.me/SPlatten>
[image: Simon Platten on about.me]

Simon Platten
about.me/SPlatten
    <http://about.me/SPlatten>

**Comment by TheSin-** [comment] 2015-06-02 15:41
I already have it fixed for you, I'm just chatting with Mottie to finalize it.

http://jsfiddle.net/1a5yu8yq/41/

**Comment by SPlatten** [comment] 2015-06-02 15:42
Excellent, well done!

On 2 June 2015 at 16:41, Justin F. Hallett <notifications@github.com> wrote:

> I already have it fixed for you, I'm just chatting with Mottie to finalize
> it.
>
> http://jsfiddle.net/1a5yu8yq/41/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mottie/tablesorter/issues/924#issuecomment-107994655>.
>



-- 
 <http://about.me/SPlatten>
[image: Simon Platten on about.me]

Simon Platten
about.me/SPlatten
    <http://about.me/SPlatten>

**Comment by Mottie** [comment] 2015-06-02 15:51
Thanks @TheSin-!

**Comment by SPlatten** [comment] 2015-06-02 15:55
What do I need to replace?

On 2 June 2015 at 16:51, Rob G <notifications@github.com> wrote:

> Thanks @TheSin- <https://github.com/TheSin->!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mottie/tablesorter/issues/924#issuecomment-107997164>.
>



-- 
 <http://about.me/SPlatten>
[image: Simon Platten on about.me]

Simon Platten
about.me/SPlatten
    <http://about.me/SPlatten>

**Comment by TheSin-** [comment] 2015-06-02 15:58
he just added the fix to git master, so just flush your cache should fix it.

**Comment by SPlatten** [comment] 2015-06-02 16:03
Ok, columns now line up, please check github for the other things I
reported, which I need to do again in the update.

On 2 June 2015 at 16:58, Justin F. Hallett <notifications@github.com> wrote:

> he just added the fix to git master, so just flush your cache should fix
> it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mottie/tablesorter/issues/924#issuecomment-107999845>.
>



-- 
 <http://about.me/SPlatten>
[image: Simon Platten on about.me]

Simon Platten
about.me/SPlatten
    <http://about.me/SPlatten>

**Comment by TheSin-** [comment] 2015-06-02 16:06
since this is github I really have no idea what you mean, if you have issues just make sure you have a report and it'll get address, I'm not sure where else you would be reporting things honestly.

**Comment by SPlatten** [comment] 2015-06-02 17:45
Ok, I'm getting some of these notifications on my gmail email account, but other articles I posted didn't come to my gmail, just on here....its all there the posts I made today.

The issues I have now, are that the data rows and header columns to not always line up, I will try to post a jsfiddle showing this if I can replicate on jsfiddle.

**Comment by TheSin-** [comment] 2015-06-02 17:48
are you using colspan at all ?

**Comment by SPlatten** [comment] 2015-06-02 17:50
No definitely not.

**Comment by TheSin-** [comment] 2015-06-02 17:50
okay make sure with your demo you provide what browser/version you are using and steps to reproduce it if there are any.

**Comment by SPlatten** [comment] 2015-06-02 17:52
ok, will do, it will have to wait until I get into work tomorrow, its 18:52 here now.

**Comment by Mottie** [comment] 2015-06-03 12:44
Closing this issue, as it is now discussed in #930.

**Closed by Mottie** 2015-06-03 12:44 UTC
Labels: Bug, Next Update, Widget
