### ISSUE TITLE
scroller demo with fixed columns shouldn't have scrollbar in left pane...

### ISSUE THREAD

**Issue by Stephen-Hazel** [Mottie/tablesorter#1506] opened 2018-01-30 21:24 UTC
In your demo here:  https://mottie.github.io/tablesorter/docs/example-widget-scroller.html 

when i use Firefox 52.2.0 there's a scrollbar for the left pane - the one with the fixed columns.
I'm guessing a width is a little messed up causing it to show when I'd expect it not to...
 
Is that fixable.  If the columns are fixed, ideally no scroll bar there ever, right?

Thanks for a SUPER FANTASTICAL AMAZING table thingy that has made my boss SUPER HAPPY !!

**Comment by Stephen-Hazel** [comment] 2018-01-30 22:20
Actuallllllllly it looks like a problem due to the jui theme.
If i swap to the blue theme, no prob !

So less of a priority for me (none at all really).
It would be niiiice to use the prettier jui theme, but I can live with blue.

**Comment by Mottie** [comment] 2018-01-30 23:17
Hi @Stephen-Hazel!

Oh, I guess I could add a jQuery UI theme selector on that page to test the other themes. Is there a particular theme you are using? Almost all of the alignment of the scroller is done with an injected stylesheet, so the styles can be overridden without including an `!important` flag.

**Comment by Stephen-Hazel** [comment] 2018-01-31 16:15
The problem is WITH the jui theme which the demo DOES use :)
I liked the look of the jui theme.  But it exhibits the problem scrollbar.
(At least on my firefox 52.2.0 !!)
When I went back to the good ole blue theme, the scrollbar is gone like it should be.

I'm totally guessing that it's due to jQuery UI's borders and padding and junk (ARGH!)
JQuery UI -looks- great, but is very fiddly with the dang padding.

With jui theme in scroller demo ON FIREFOX 52.2.0,
You can see the scrollbar in bottom left on the pane that doesn't need side scrolling.
There's also a static rectangle (that's probably there to space the bottom properly).

With blue theme, everything is cool.

So now I'm just using the blue theme and there's no emergency.
But it wouuuuuld be nice to use that fancy jui theme some dayyy :)

Thanks for your AMAZIN COOOODE - I love eeeeet !!

**Comment by InhumanSoul** [comment] 2018-02-05 11:50
I can confirm this bug in Firefox 52.6.0. The jQuery UI theme seems to be the only theme with this problem.

**Comment by Mottie** [comment] 2018-02-05 19:52
I did a little tweaking of the scroller widget to account for jQuery UI spacing. Now it works in *almost* all jQuery UI themes. I'm not sure why there are 4 or 5 themes that still show the horizontal scroll bar.

**Comment by Mottie** [comment] 2018-03-18 14:55
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Closed by Mottie** 2018-03-18 14:55 UTC
Labels: Bug, How To..., Themes, Widget, Widget-Scroller
