### ISSUE TITLE
TypeError: $column.val(...).trigger is not a function in jquery.tablesorter.combined.js

### ISSUE THREAD

**Issue by SPlatten** [Mottie/tablesorter#930] opened 2015-06-03 06:34 UTC
I caught this error by wrapping the initialisation of tablesorter and tablesorterPager with a try / catch clause.

```javascript
  try{
    if ( !($('#tk_tblrpt') 
        && $('#tk_tblrpt').length > 0 
        && $('#tk_tblrpt').tablesorter) ) {
      return;
    }
    $('#tk_tblrpt').tablesorter({
      theme: 'blue'
      ,headerTemplate: '{content}'
      ,widgets: ['zebra', 'filter', 'scroller']
      ,widgetOptions: {
        scroller_height: 400
        ,scroller_fixedColumns: 2
        ,scroller_rowHighlight: 'hover'
        ,zebra : [ 'even', 'odd' ]
      }
    }).tablesorterPager({
      container: $('.pager')               
      ,fixedHeight: false
    });
  } catch(ex) {
    var strMsg = ex;            //Breakpoint here in firebug triggers when error occurs
  }   
```

The error reported is on line 4068, where i is referencing the array setFilters but it the array is 0 length.  The fix was simple:

```javascript
            if ( i < setFilters.length ) {
              var objFilter = setFilters[ i ];
              
              if ( objFilter ) {              
                          $column.val( objFilter ).trigger( 'change.tsfilter' );
              }
            } 
```
I'm not sure if this points to another issue.

**Comment by Mottie** [comment] 2015-06-03 12:43
Ok, I like to think I have a lot of patience, but man you're really pushing it....

Why are you opening a new issue? We have already discussed this exact same problem in #920  and [#924](https://github.com/Mottie/tablesorter/issues/924#issuecomment-107965089), and you even posted the same code fix in the last issue.

**PLEASE, stop opening the exact same issue more than once.**

Just because an issue is closed doesn't mean you can't continue the discussion in that thread.

----

So what version of jQuery are you using? If I enter the following into the developer console, I *DO NOT* get any errors (try it on this page even, it works & GitHub is currently using v2.1.3):

```js
var x = [];
$('input:eq(0)').val( x[4] ).trigger( 'test' );
```

So, it shouldn't matter if `setFilters[ i ]` is `undefined`. jQuery does not produce an error.

Again, I ask... please *make me a demo reproducing this error* so I can troubleshoot it. I added the above code to [this demo](http://jsfiddle.net/1a5yu8yq/45/) and I am still not able to reproduce it.

**Comment by SPlatten** [comment] 2015-06-03 13:41
jQuery JavaScript Library v2.1.4

**Comment by Mottie** [comment] 2015-06-03 16:32
Javascript is much more forgiving, it does not cause errors when you manipulate arrays. The value just returns as `undefined`.

Yes, you do need a demo to show me the error; this issue is not obvious... why do you think we've had this difficulty across 3 issues now?

**Comment by SPlatten** [comment] 2015-06-03 16:50
Javascript does throw an exception when you  try to reference an undefined element, thats how I trapped it in the first place, with a try / catch clause.

I will try and replicate and post somemthing.

**Comment by Mottie** [comment] 2015-07-28 21:35
I have tried everything to duplicate this issue including testing the [Bootstrap demo](http://mottie.github.io/tablesorter/docs/example-widget-bootstrap-theme.html) in which I wrapped the initialization code in a try/catch function and added an initial filter search. No exception was thrown.

I'm going to go ahead and close this issue. If you can create a demo showing this problem, then I would be happy to investigate the issue further. Also, please feel free to continue the discussion in this thread instead of opening a new issue.

**Closed by Mottie** 2015-07-28 21:35 UTC
