### ISSUE TITLE
onEditComplete fired twice on blur

### ISSUE THREAD

**Issue by davdtm** [Mottie/tablesorter#902] opened 2015-05-08 05:19 UTC
It seems that the event onEditComplete is fired twice if I leave the edit field by clicking outside it or using the tab button (blur), by the way in such a case if an handler is associated to the editComplete event the blur event is not triggered at all. On the contrary, if I set the "editable_enterToAccept" option to true and I click the enter button, the editComplete event is correctly fired once. So two questions: 1) is it expected that the editComplete event may be triggered twice in some cases? 2) it is expected that by associating a callback to such event, this disables the blur event?

Thanks

**Comment by Mottie** [comment] 2015-05-08 13:00
Hi @davdtm!

I modified a demo locally and I could not reproduce this issue.

1. The "editComplete" event should only fire once and I could not duplicate this issue. Are you sure you're not binding to it twice?
2. The blur event callback was always being called.

Then, I created [this jsFiddle](http://jsfiddle.net/Mottie/xxmha2Ly/6/) (linking to code in the master branch) and noticed that the "editComplete" was still only firing once, but the blur callback was not firing at all...

Oddly, it started working again when I switched from using the jQuery-edge version to jQuery v1.11.0 (v2.1.3 works fine too). I tried and failed to duplicate this issue with just a contenteditable element and the edge version...

Hopefully something I posted above helps fix the issue.

**Comment by davdtm** [comment] 2015-05-08 14:39
Mottie, thanks for looking into it. I did not add tech details in my bug submission because my case is slightly complex, involving different widgets. I'll try to further dig into it (maybe simplifying my case) and use your jsFiddle to see whether I can reproduce there the same conditions I have here.

Thanks for now

**Comment by davdtm** [comment] 2015-05-08 14:42
By the way, do you have any suggestion to help me debugging the problem? Maybe something like what triggers that event (i.e., tablesorter widgets can do that?) or whatever you may consider useful to track the event history...

**Comment by Mottie** [comment] 2015-05-08 15:35
The [`$.tablesorter.editable.editComplete` function](https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-editable.js#L12-L22) is called whenever the widget wants to trigger the edit complete event/callback. I made it a separate function to allow customizing it.

You can also check to see what events are bound to the table by typing the following into the console:

```js
$._data( $('table')[0] ).events
```

`$._data()` is the internal jQuery data function and will have an array of more than one item for the editComplete function if it is bound more than once.

**Comment by davdtm** [comment] 2015-05-08 23:05
Mottie, thanks so much. I guess I'm closer to understand what's going on but I still miss some little step. If I set the option 

editable_editComplete  : 'foo'

and I attach a handler as follows:

jQuery('#my_tablee').on('foo','td',function(event,config)
{
alert('triggering foo');
});

I get the alert twice. But, if I DON'T specify at all the "editable_editComplete" option, and I set the handler as 

jQuery('#my_tablee').on('editComplete','td',function(event,config)
{
alert('triggering foo');
});

I get the alert only once. I thought that the "editable_editComplete" option was just to "rename" the event fired as the editing is complete, but I guess I was wrong. Am I adding another event instead of renaming it?

sorry for the stupid question but... you did a fantastic job I'd love to better understand how it works!

**Comment by davdtm** [comment] 2015-05-08 23:32
it should be something related to the 'td' I've added as selector in the "on()" bound. If I remove the 'td' selector it seems I get the editComplete event triggered once, otherwise twice. The fact that this does not happen in your jsfiddle example may suggest that there's something strange in my implementation

**Comment by Mottie** [comment] 2015-05-09 00:06
I wonder if you are catching the editComplete as it is bubbling up from the `td` to the `table`?

It might be better to not use delegated events since you can't stop them from bubbling up the DOM tree. Instead, just bind to the "editComplete" event on the table and use the `event.target` to get the element. Something like this:

```js
$('table').on('editComplete', function(e){
    // the "editComplete event is triggered on the div within the cell
    var $this = $( e.target ).closest('td');
    /// do whatever
});

**Comment by davdtm** [comment] 2015-05-09 00:10
OK, I've understood the problem. As side effect of the editComplete event, in the callback function I edited the string (changing the case) and re-set it into the editable div with $div.text(my_string);
This last step triggered the editComplete event a second time. It's definitively NOT a tablesorter bug, so I'm sorry for having wasted your time. Thanks for your help

**Comment by Mottie** [comment] 2015-05-09 00:14
No worries, I'm glad you found the issue :smiley_cat:

**Comment by Mottie** [comment] 2015-06-30 15:12
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.

**Closed by Mottie** 2015-06-30 15:12 UTC
Labels: How To..., Widget, Widget-Editable
