### ISSUE TITLE
How to update from 2.17.7 to latest?

### ISSUE THREAD

**Issue by OmgImAlexis** [Mottie/tablesorter#1033] opened 2015-10-05 13:14 UTC
Currently on a project I'm working on we're using the old version of tablesorter from before you forked it and I was hoping to update to the version you maintain, specifically the version of bower. All's well and it updates fine but I've found it's basically been rewritten and the table now doesn't layout correctly with different widths on columns, etc. and `$.tablesorter.columnSelector.attachTo( $('#showListTableShows'), '#popover-target');` doesn't seem to work at all anymore, has this been updated to a new function?

**Comment by Mottie** [comment] 2015-10-05 15:33
Hi @OmgImAlexis!

Sorry, are you updating from 2.0.5b or 2.17.7?

There are a few substantial differences between 2.0.5b and the current version. In the [documents](http://mottie.github.io/tablesorter/docs/) you can see which options have been [deprecated and/or removed](http://mottie.github.io/tablesorter/docs/#deprecated).

If you mean there are changes from 2.17.7 to the current that have causes the column selector widget to stop working. You can see a list of changes to the widget in the [notes](http://mottie.github.io/tablesorter/docs/example-widget-column-selector.html) section. Maybe you could try the [`refreshColumnSelector` method](http://mottie.github.io/tablesorter/docs/example-widget-column-selector.html#methods).

It would be easier to help if you could provide a demo of the issue. I have this [jsFiddle demo](https://jsfiddle.net/Mottie/mcn8o3yu/) that you can modify to show me the problem.

**Comment by OmgImAlexis** [comment] 2015-10-05 15:57
The version we currently have is listed like so in the minified file so I'm assuming `2.17.7`.
````
/*!
* TableSorter 2.17.7 min - Client-side table sorting with ease!
* Copyright (c) 2007 Christian Bach
*/
````

From the looks of it we may have to a full rewrite of our code that depends on this. [Here](https://github.com/SiCKRAGETV/SickRage)'s the project.
The top one is with `2.17.7` and the bottom with the latest bower version.
![screen shot 2015-10-06 at 2 26 41 am](https://cloud.githubusercontent.com/assets/6525926/10285737/bbd943c6-6bd1-11e5-85fc-eb4bf7773ecf.png)
![screen shot 2015-10-06 at 2 26 13 am](https://cloud.githubusercontent.com/assets/6525926/10285753/cf9eb012-6bd1-11e5-9328-34dd4f2b5427.png)

**Comment by thezoggy** [comment] 2015-10-05 16:24
note that sickrage (fork of sickbeard) is using tablesorter (mottie) 2.17.7, widgets is 2.16 (back before we kept the versions in sync).

https://github.com/SiCKRAGETV/SickRage/blob/master/gui/slick/js/lib/jquery.tablesorter.widgets-2.17.7.min.js
> `/*! tableSorter 2.16+ widgets - updated 8/9/2014 (v2.17.7) */`

thus looking at changelog @ 2.17.7 which is 1+ year old now:
https://github.com/Mottie/tablesorter/wiki/Changes#m2.17

upgrading tablesorter is usually a painless thing, just drop in the new files and go. as most of the time features are added not removed  and rarely is old params renamed (even if they are, old ones are usually still supported for backwards compatibility). now with that said, there are times where there is a bug fix / update that you may want to adjust some code to take use of. like the 2.17.8 upgrade that allowed to some things on the sb history page to make things better to search for.

ex, 2.17.8 upgrade and changes to sb code to take use of it:
https://github.com/midgetspy/Sick-Beard/pull/877

to upgrade any js lib you ideally should upgrade patch->minor->major. so you deal with less updates/changes. or just jump to latest and deal with whatever fixes you need. both have their pro/cons.

**Comment by OmgImAlexis** [comment] 2015-10-05 16:27
@thezoggy were planning on moving straight to the newest version but since none of the js libraries were kept in sync or even documented in some cases this is why I opened this issue incase there was something I was completely overlooking like a migration plugin from the old setup or something. From the looks of it as long as I can workout the layout issue with the widths being different to how it use to I can fix everything else.

**Comment by thezoggy** [comment] 2015-10-05 16:30
not sure what there is to document if the version numbers are in the filename and git history shows when they were applied/changes made with them. but anyways maybe dont make such a huge jump..  go from 2.17.x to 2.20.1, make sure things are good then go to next minor version, rinse and repeat until you see issues.. address them and continue. jumping 1+ year in commits makes it hard to bisect where the issue is (if its even with the lib you think it is)

**Comment by OmgImAlexis** [comment] 2015-10-05 16:32
@thezoggy alright, I may have to do that. The main issue I had was the fact that the version numbers on bower didn't seem to match up and we're currently using a version before mottie even took over.

**Comment by thezoggy** [comment] 2015-10-05 16:39
if your not using mottie's tablesorter.. dont know how you'd expect to upgrade to his from someone elses code. also we dont have anything to do with bower.. and you may be looking at a different persons version of tablesorter..

**Comment by OmgImAlexis** [comment] 2015-10-05 16:42
@thezoggy I'm a dev with SickRage and we're moving everything to bower, that has nothing to do with SickBeard that you maintain.

**Comment by thezoggy** [comment] 2015-10-05 16:44
I know who you are, and yes SR has to do with SB (which i dont maintain, left awhile ago for Sonarr)

**Comment by Mottie** [comment] 2015-10-31 16:33
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Closed by Mottie** 2015-10-31 16:33 UTC
Labels: How To..., Widget, Widget-ColumnSelector
