### ISSUE TITLE
IE and Edge Slow when 2000+ records

### ISSUE THREAD

**Issue by pedrojrivera** [Mottie/tablesorter#1462] opened 2017-10-05 14:32 UTC
Hello,

I have a situation when loading 2000+ records takes a few seconds in Chrome but in Edge and Explorer it can take upwards of 15 to 30+ seconds.

Here is my config:

```js
function setTableSorter() {
  var pagerOptions = {
    container: $(".ts-pager"),
    cssGoto: ".pagenum",
    ajaxUrl: null,
    customAjaxUrl: function(table, url) {
      return url;
    },
    ajaxError: null,
    ajaxObject: { dataType: "json" },
    ajaxProcessing: null,
    processAjaxOnInit: false,
    output: "{startRow} to {endRow} of {totalRows}",
    updateArrows: true,
    page: 0,
    size: 20,
    savePages: false,
    pageReset: 0,
    fixedHeight: false,
    removeRows: false,
    countChildRows: false
  };

  $("table.tablesorter")
    .tablesorter({
      theme: "bootstrap",
      delayInit: true,
      widthFixed: true,
      headerTemplate: "{content} {icon}",
      widgets: ["uitheme", "filter", "math"],

      widgetOptions: {
        filter_cssFilter: "form-control input-sm",
        filter_hideFilters: false,
        filter_ignoreCase: true,
        filter_searchDelay: 300,
        filter_external: ".search"
      }
    })
    .tablesorterPager(pagerOptions);
}
```

I initially load 200 records using:

```
var $rows = $(data);
$('#tableInventory tbody').html($rows).trigger("update", [false]);
```

DATA  is the html returned from ajax call with rows to append to table.

Then I make multiple ajax calls to load up the rest of the data:

`$('#tableInventory').find('tbody').append($rows);`

I noticed that **update** gets really slow in Explorer and Edge after 1000+ records. So I decided to append all subsequent records with <TR> style = displaye:none and issue an update at the end,

I also tried using the following:

`$('#tableInventory tbody').append($rows).trigger("addRows", [$rows, false]);`

I get an error message stating "length" error on undefined. 

I changed the line of code to:

`$('#tableInventory tbody').append(data).trigger("addRows", [$rows, false]);`

I used data as instead of $rows. The error went away. The rows get appended, but the pager doesn't get updated.

Any ideas?

**Comment by Mottie** [comment] 2017-10-06 02:03
Hi @pedrojrivea!

If you're using the pager, you shouldn't need to append rows or trigger any events to update the table.

Make sure to check out the [demo](https://mottie.github.io/tablesorter/docs/example-pager-ajax.html) which includes the code at the bottom of the page. There are multiple methods to process the raw data for addition to the table; see the [ajaxProcessing](https://mottie.github.io/tablesorter/docs/#pager-ajaxprocessing) documentation for more details.

**Comment by pedrojrivea** [comment] 2017-10-06 21:04
The problem is that I have a dropdown box that when the value changes it clears the table, executes an ajax call to fetch records and then adds them to the table. So this function is outside of the pager control.

**Comment by pedrojrivea** [comment] 2017-10-08 13:29
Hey @Mottie,

I think I sorted it all out. I implemented the ajax processing similiar to the demo you provided. So now paging, filtering, and sorting happens server side. 

The only thing I am not sure of is that I have a dropdown box that exists outside the table. When a user changes its value I have to refresh the table with new data. The value in the dropdown does not represent any visible data in the table columns. It's more of a status of a process. 

I could not figure out how to properly invoke the tables ajax process when the dropdown value changed.

I ended up just re-initializing the tableSorter object which seems to work.

**Comment by Mottie** [comment] 2017-10-08 14:01
You can tie the dropdown to the pager by triggering one of the pager methods like set [pageAndSize](https://mottie.github.io/tablesorter/docs/#pageandsize):

```js
$('table').trigger('pageAndSize', [ 2, 20 ]);
```

And listening for when the [pager has completed](https://mottie.github.io/tablesorter/docs/#pagercomplete):

```js
$('table').bind('pagerChange pagerComplete', function(event, options) {
  // options = table.config.pager (pager addon)
  // options = table.config (pager widget) - so use options.pager.page below
  // this.totalPages contains the total number of pages
  // ==> update the dropdown here
});
```

I'd need to see the dropdown HTML/code to give a more specific answer, if you need it still.

**Comment by pedrojrivea** [comment] 2017-10-08 16:50
@Mottie ,

Unless I'm misunderstanding what you are saying, I believe I want to do this in the opposite direction.  

When the dropdown value changes, trigger the table to invoke ajax call and update table. 

Here's my dropdown:

```
<select name="DATSTAT" id="DATSTAT" onChange="getRecords();">
<option value="P">Pending</option>
<option value="I">In Progress</option>
<option value="R">Ready to Transmit</option>
<option value="T">Transmitted</option>
</select>
```

At this point getRecords() gets invoked and in this function I want to invoke the table to call its ajax function. 

Hope this makes sense.

Thanks!

**Comment by Mottie** [comment] 2017-10-08 17:07
The `getRecords` function should then set the filter, page and/or page size. Something like this:

```js
function getRecords() {
  var $table = $('table'),
    filters = [];
  // update whichever column needs to be updated
  filters[2] = $("#DATSTAT").val();
  // update filters, but don't apply the search
  $.tablesorter.setFilters( $table, filters, false );
  // go back to page 1 with 20 entries per page
  $table.trigger("pageAndSize", [1, 20]);
}
```

If you're not using the filter to switch data sets, then use the `customAjaxUrl` callback function to alter the ajax url.

Ref:

* [`setFilters`](https://mottie.github.io/tablesorter/docs/#function-setfilters)
* [`pageAndSize`](https://mottie.github.io/tablesorter/docs/#pageandsize)
* [`customAjaxUrl`](https://mottie.github.io/tablesorter/docs/#pager-customajaxurl)

**Comment by pedrojrivea** [comment] 2017-10-08 17:51
The pageAndSize trigger doesn't fire all the time.  It only seems to fire if I set the page or size to something other than what is currently set. Here is my function:

```
function getRecords()
{
	// Capture filter data
	var data = $.tablesorter.getFilters( $('#tableInventory') );

	// Clear filter data
	var filter = $.tablesorter.getFilters( $('#tableInventory') );
	for (var i = 0; i < filter.length; i++) {
		filter[i] = '';
	}
	$.tablesorter.setFilters( $('#tableInventory'), filter, false);
	
	// Show progress indicator
	$("#loadingrecs").show();

	// Reset pager and table
	$('#tableInventory').trigger('pageAndSize', [ 1, $('#tableInventory')[0].config.pager.size ]);
	//setTableSorter();
}
```

Am I doing something wrong?

**Comment by pedrojrivea** [comment] 2017-10-08 18:05
Here is my ajax config:

```
		ajaxUrl: '/hbaraw/wcsa10a.pgm?page={page}&size={size}&{filterList:fcol}&{sortList:col}&',

		customAjaxUrl: function(table, url) { 
			url += 'key='    +  encodeURIComponent($('#key').val()) + '&' +
			       'fndyr='  + '&' +
			       'fndnum=' + '&'+ 
			       'memnum=' + '&' + 
			       'memsub=' + '&' +
			       'seqnum=' + '&' +
			       'datstat=' + encodeURIComponent($('#DATSTAT').val()) + '&' +
			       'action=LOADRECS' ;

			// If no filters, remove extra parm
			url = url.replace('&fcol&', '&' );

			// If no sorting, remove extra parm
			url = url.replace('&col&', '&' );

			return url; 
		},

		ajaxError: null,
		ajaxObject: { type: 'GET',
					  dataType: 'text',
					  contentType: 'application/x-www-form-urlencoded; charset=UTF-8'
					 },

		ajaxProcessing: function(data) {
			var p1 = data.indexOf("{");
			var p2 = data.indexOf("}");
			var tr = data.substring(p1, p2+1);
			var totalrows = $.parseJSON(tr).total_rows;
			var $rows = $(data.substring(p2+1));
			return [totalrows, $rows, null];
		},

		processAjaxOnInit: true,

```

**Comment by pedrojrivea** [comment] 2017-10-08 18:14
@Mottie ,

Ok...I think I figured it out. I used this instead:

`$('#tableInventory').trigger('pagerUpdate', 1);`

This worked as I expected. Perfect!

**Comment by Mottie** [comment] 2017-10-08 18:19
Ok cool!

Yeah, if the page and size don't change, the internal code prevents a new ajax call; to get around this use `"pagerUpdate"` as you discovered.

And YAY! I'm glad you got it all working 😸

**Comment by pedrojrivea** [comment] 2017-10-08 18:22
Yes...perfect!!! Now I am able to load this screen that has 200k + records. Each page loads <1 second. So sweet!!! Thanks for your guidance.

**Comment by Mottie** [comment] 2017-12-13 21:46
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Closed by Mottie** 2017-12-13 21:46 UTC
Labels: How To..., Pager
