### ISSUE TITLE
Sticky Column

### ISSUE THREAD

**Issue by mworsnop** [Mottie/tablesorter#804] opened 2015-01-23 21:22 UTC
Is there a way to stick the left column just like the sticky header except for the left column?

**Comment by Mottie** [comment] 2015-01-24 22:19
Hi @mworsnop!

There is no current method to make a column sticky. I do plan on adding support for this soon.

Closing this issue as it is a duplicate of #135.

**Closed by Mottie** 2015-01-24 22:19 UTC

**Comment by Mottie** [comment] 2015-03-26 15:55
Check out the last table in the [scroller widget demo](http://mottie.github.io/tablesorter/docs/example-widget-scroller.html#group)... :grinning:
