### ISSUE TITLE
intermittent console message: "t.addWidget is not a function"

### ISSUE THREAD

**Issue by bogal** [Mottie/tablesorter#1489] opened 2017-12-30 23:14 UTC
I've noticed in my logs that every now and then i get the following javascript message (FF Dev Edition):

> TypeError: t.addWidget is not a function     jquery.tablesorter.widgets.min.js:2:2565
> <anonymous>
> http://mydomain.co.uk/assets/tablesorter/dist/js/jquery.tablesorter.widgets.min.js:2:2565
> <anonymous>
> http://mydomain.co.uk/assets/tablesorter/dist/js/jquery.tablesorter.widgets.min.js:2:1622
> <anonymous>
> http://mydomain.co.uk/assets/tablesorter/dist/js/jquery.tablesorter.widgets.min.js:2:166
> <anonymous>
> http://mydomain.co.uk/assets/tablesorter/dist/js/jquery.tablesorter.widgets.min.js:2:2

I do not get this every time i load the page, and cannot seem to reliably reproduce it. It just seems to happen every now and then. When this happens, tablesorter fails to load / doesn't appear on the tables on the page. Any idea why? Refreshing the page fixes the problem.
The order of the scripts loaded in my <head> tag:

```
<script type="text/javascript" src="/assets/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="/assets/bootstrap/dist/js/bootstrap.min.js"></script>
<script type="text/javascript" async="async" src="/assets/tablesorter/dist/js/jquery.tablesorter.min.js"></script>
<script type="text/javascript" async="async" src="/assets/tablesorter/dist/js/jquery.tablesorter.widgets.min.js"></script>
```

**Comment by Mottie** [comment] 2017-12-31 00:42
Hi @bogal!

I believe the problem is because the `async` property is set on both the tablesorter and widget scripts. The widget script *requires* that the tablesorter script is loaded first.

**Comment by bogal** [comment] 2017-12-31 15:58
Thanks for the quick reply. Will remove the async properties and see if it helps :)

**Comment by Mottie** [comment] 2018-02-25 19:17
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Closed by Mottie** 2018-02-25 19:17 UTC
Labels: How To...
