### ISSUE TITLE
Disable/enable tablesorter

### ISSUE THREAD

**Issue by pungitopo** [Mottie/tablesorter#1075] opened 2015-11-06 16:33 UTC
Hello Mottie, first thank you for your plugin.

I'd like to know if there is a simile way to disable and the enable again tablesorter (the sort and the filter). The pager disable/enable works great but i did not find any way to do the same with sort and filter column.

Thank you for your support.

Bye

**Comment by Mottie** [comment] 2015-11-06 19:39
Hi @pungitopo!

This is a duplicate of #117, but I'll look into adding something soon.

In the mean time, if you really need to stop sorting & filtering, you'll need to [destroy](http://mottie.github.io/tablesorter/docs/#destroy) tablesorter. To "enable" tablesorter, you'll have to re-initialize it again.

Note: there is an issue open about a memory leak (#1034) in the destroy method which I haven't been able to isolate.

**Comment by pungitopo** [comment] 2015-11-07 09:20
Hi @mottie, the destroy option cause the change of the layout. Is there a way to avoid it or at least unbind the sort and filter ?

Thank you

**Comment by Mottie** [comment] 2015-11-07 15:19
Did you try?

```js
// Remove tablesorter and all classes but the "tablesorter" class on the table
$('table').trigger('destroy', false);
```

Or better yet, test out this 'toggle-ts' widget I just wrote ([demo](http://jsfiddle.net/Mottie/a13cp6wn/)).

So far, it only has one option:

```js
$('table').tablesorter({
	theme: 'blue',
	widthFixed : true,
	widgets: ['zebra', 'filter', 'toggle-ts'],
	widgetOptions : {
		toggleTS_hideFilterRow : filterRow
	}
});
```

With it you can enable or disable the sort & filter. If you want to disable the pager, continue to use "enablePager" & "disablePager".

**Comment by Mottie** [comment] 2015-11-08 16:51
New widget added in https://github.com/Mottie/tablesorter/commit/60ea78eea686f03a822865027bcba625f3303ea6.

**Comment by pungitopo** [comment] 2015-11-09 15:31
Hi @Mottie,

I tested your new widget.
It works perfectly.
I hope we'll find it in the next release.

Thank you again.

Bye,
  Pungitopo

**Comment by Mottie** [comment] 2015-11-10 22:04
Version 2.24.4 is now available with this widget - [Toggle widget demo](http://mottie.github.io/tablesorter/docs/example-widget-toggle-tablesorter.html).

**Closed by Mottie** 2015-11-10 22:04 UTC
Labels: Enhancement, How To..., Next Update, Widget

**Comment by jpbeast** [comment] 2019-10-31 13:09
> Did you try?
> 
> ```js
> // Remove tablesorter and all classes but the "tablesorter" class on the table
> $('table').trigger('destroy', false);
> ```
> 
> Or better yet, test out this 'toggle-ts' widget I just wrote ([demo](http://jsfiddle.net/Mottie/a13cp6wn/)).
> 
> So far, it only has one option:
> 
> ```js
> $('table').tablesorter({
>     theme: 'blue',
>     widthFixed : true,
>     widgets: ['zebra', 'filter', 'toggle-ts'],
>     widgetOptions : {
>         toggleTS_hideFilterRow : filterRow
>     }
> });
> ```
> 
> With it you can enable or disable the sort & filter. If you want to disable the pager, continue to use "enablePager" & "disablePager".

@Mottie 

Thanks for this solution.
I was searching for almost 7 hours and also tried many different ways to achieve this.
