### ISSUE TITLE
Resizable columns don't work quirte right with multi-line text cells

### ISSUE THREAD

**Issue by gbjbaanb** [Mottie/tablesorter#914] opened 2015-05-21 09:41 UTC
I have a table with 7 columns, that has data that 'wraps' to multiline for 2 of these columns. The first column is always multi-line as its a full date description. 

When trying to resize, resizing the columns on the right work great, but resizing the first column can be hit and miss. It has a tendency to flicker and resize the column between the full width of text and width of the first word of text no matter how far to the right I drag.

I have the column set to use all 100% of the page width. 

Has anyone else seen this behaviour? Is it a niggle with the resizing code that attempts to fit columns in?

I think the solution is to ensure the currently-being-resized column is always set to the user's desired width and only the other columns get auto-resized. 

Quick partial screenshot, showing the first column that won't resize to a single row of text.
![capture](https://cloud.githubusercontent.com/assets/6808175/7745787/ae128d6c-ffa5-11e4-84fd-1f5d41b1e112.JPG)

**Comment by Mottie** [comment] 2015-05-21 15:53
Hi @gbjbaanb!

I am not seeing the behavior being described. I set up [this demo](http://jsfiddle.net/1wxxgynh/1/) with the date in the first column and I have no trouble resizing it. I did have to add a space between "Date" and "Time" to allow the column to narrow even further since the resizable widget minimum width is limited by the text of the header.

If I am mistaken about the issue being reported here, please modify the demo to reproduce the problem.

**Comment by gbjbaanb** [comment] 2015-05-22 08:45
Thank you. What I see in your demo (on Firefox 38)  is that you can resize the date column, but only to a certain extent - which is understandable given the small frame width.

I am running the code on IE within a CHtmlCtrl - which gives me an IE8 renderer.

I think there is also something interesting going on with the size of the window, as I've copied my code into jsfiddle and it works, unless I resize the output pane to a smaller size - but too small and it works correctly as there's not enough space to perform resizing. Even then, it seems fine in firefox regardless. 

I could be running jsfiddle in IE under compatibility mode for IE8 wrongly however - its a royal PitA! 

I shall have a look at the js you supplied in your demo and see if the other stuff in mine is getting involved, but thank you for the quick response!

**Comment by Mottie** [comment] 2015-05-22 12:54
Yeah, IE8 (even compatibility mode) won't work in jsFiddle or jsBin.

If you copy that page locally and run the page in IE8, I only have IE11 set to IE8 compatibility mode, it appears to work without any issues.

**Comment by Mottie** [comment] 2015-06-30 15:16
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.

**Closed by Mottie** 2015-06-30 15:16 UTC
Labels: How To..., Widget, Widget-Resizable
