### ISSUE TITLE
Disable Sorting while keeping the Filter & ColumnSelector widgets running?

### ISSUE THREAD

**Issue by crazyserb** [Mottie/tablesorter#1354] opened 2017-02-05 21:32 UTC
Is there any way to attach .tablesorter to a table but disable the whole sorting functionality and keep the filter & columnselector and any other widgets? 

As I've got a data set of 1,000 records and just initially loading them all in for sorting crashes the page half the time... so I wanna disable that and implement some other PHP based sorting instead.

**Comment by TheSin-** [comment] 2017-02-05 22:01
there are 2 options, add noSort option to each col, OR use the pager with Ajax and do server side sorted/filtering via php that is what I do.

**Comment by crazyserb** [comment] 2017-02-05 22:04
Server side sorting/filtering via PHP and pager with ajax? 

Ok, go on... do you have any code examples of that? That might be a much better solution than having to re-code this whole thing my own way...

**Comment by TheSin-** [comment] 2017-02-06 00:12
I don't currently but maybe this week I can find time to make a gist I'll have to try and rip it out of my classes but I should be able to get enough out to make sense of it all.

**Comment by Mottie** [comment] 2017-02-06 04:00
Hey @crazyserb!

You can set the [`serversideSorting` option](https://mottie.github.io/tablesorter/docs/#serversidesorting) to `true` to disable sorting on the client-side.

If you want to delay the initial processing, then set the [`delayInit` option](https://mottie.github.io/tablesorter/docs/#delayinit) to `true`... then once the user uses a widget that needs the cache, it will then be processed, so they will then experience any delay at that point. The problem is any preset or saved filters will cause the initial cache processing even with the `delayInit` set.

If you want to remove the sort arrows, then you'll have to set each column header with a `sorter-false` class name.

**Comment by Mottie** [comment] 2017-04-02 13:20
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Closed by Mottie** 2017-04-02 13:20 UTC
Labels: How To...
