### ISSUE TITLE
Select2 

### ISSUE THREAD

**Issue by wguerrero42** [Mottie/tablesorter#1794] opened 2021-06-24 22:27 UTC
Hello, 

I had to build an MS Excel like filter, and I found a demo of TableSorter with Select2 in the wiki page, that example wasn't working with the current version of Select2, so I managed to make select2 work again with TableSorter. I made a few improvements, and there might be more to come.

TableSorter: v2.31.3
Select2: v4.1.0-rc.0

Thank you Mottie, TableSorter is awesome!

[widget-filter-formatter-select2.min.txt](https://github.com/Mottie/tablesorter/files/6712384/widget-filter-formatter-select2.min.txt)

**Comment by Mottie** [comment] 2021-06-25 01:31
Hi @wguerrero42!

This is a duplicate of https://github.com/Mottie/tablesorter/issues/1216 - and sorry, I've been so busy lately that I have little time to work on these projects 😿

**Closed by Mottie** 2021-06-25 01:31 UTC
