### ISSUE TITLE
Part of the thead scrolls off the screen when scrolling up

### ISSUE THREAD

**Issue by jdlaisd** [Mottie/tablesorter#1357] opened 2017-02-14 16:12 UTC
The report has lots of columns so the header is 6 lines high in some columns. When I scroll up, only 3 of the column header lines display. 

Before scrolling:
![image](https://cloud.githubusercontent.com/assets/23642766/22937087/18877752-f29d-11e6-92e2-d3c3f5b2dac4.png)

After scrolling: 
![image](https://cloud.githubusercontent.com/assets/23642766/22937108/3557120c-f29d-11e6-9a1f-92e38693361c.png)

**Comment by Mottie** [comment] 2017-02-14 17:41
Hi @jdlaisd!

What widget(s) are you using? Also, please share any initialization code you are using. It would be awesome if you could modify [this demo](https://jsfiddle.net/Mottie/bbxxomhx/) to show the problem, to make it easier for me to troubleshoot.

**Comment by jdlaisd** [comment] 2017-02-14 19:31
Thanks VERY MUCH for your quick reply. I love your tablesorter and the filters are very handy. I modified the header by adding the <br> tags in the header data. When you make the window smaller so you have to scroll, you can see that the top part of the first column's header is cut off.


[cid:d39a1650-5368-4aa7-8e8b-f7dd5c488250]


Jade Lindquist

Learner · Individualization · Responsibility · Achiever · Relator

Management Information Systems
Austin Independent School District
(512) 414-9234


________________________________

**Comment by Mottie** [comment] 2017-02-14 21:22
Ok, so I created [this demo](https://jsfiddle.net/Mottie/bbxxomhx/342/) and I still have not been able to duplicate the problem. Please update it to show the problem. Thanks!

**Comment by jdlaisd** [comment] 2017-02-15 14:29
Hi Rob,


Before I replied to your previous email, I updated the jsfiddle that you sent me: https://jsfiddle.net/bbxxomhx/341/

Tablesorter demo - JSFiddle<https://jsfiddle.net/bbxxomhx/341/>
jsfiddle.net
Test your JavaScript, CSS, HTML or CoffeeScript online with JSFiddle code editor.




and when you make your screen smaller such as in the screenshot below, the top of the sticky header scrolls off. I don't see sticky headers in the demo you sent me: https://jsfiddle.net/Mottie/bbxxomhx/342/

Tablesorter demo - JSFiddle<https://jsfiddle.net/Mottie/bbxxomhx/342/>
jsfiddle.net
Test your JavaScript, CSS, HTML or CoffeeScript online with JSFiddle code editor.




[cid:c244e60e-172b-4d68-b33a-8a56f795bcf2]


Jade Lindquist

Learner · Individualization · Responsibility · Achiever · Relator

Management Information Systems
Austin Independent School District
(512) 414-9234


________________________________

**Comment by Mottie** [comment] 2017-02-15 16:57
Oh, sorry you never mentioned the sticky headers widget. It is still odd though as I can't reproduce the problem... https://jsfiddle.net/Mottie/bbxxomhx/343/

**Comment by jdlaisd** [comment] 2017-02-15 17:08
Thanks so much for looking into it. I just added <br> 3 times to the top of each value in the table header for my report so when the user scrolls down, he can still see the data. In your last jfiddle, when I scroll down, the header moves up a little (just not as much as it does with my report). It's still very usable and an awesome plugin. Thanks so much for contributing it and for trying to reproduce the problem. It might be our js/css is overriding something in yours.


Jade

Learner · Individualization · Responsibility · Achiever · Relator

Management Information Systems
Austin Independent School District
(512) 414-9234


________________________________

**Comment by Mottie** [comment] 2017-02-15 18:05
Worse case scenario, you can add this bit of CSS to move the sticky header down ([demo](https://jsfiddle.net/Mottie/bbxxomhx/344/))...

```css
.tablesorter-sticky-wrapper {
  padding-top: 20px;
  background: white;
}
```

Adjust the `padding-top` to make everything visible.

**Comment by jdlaisd** [comment] 2017-02-16 19:44
Thanks very much Rob!


Jade

Learner · Individualization · Responsibility · Achiever · Relator

Management Information Systems
Austin Independent School District
(512) 414-9234


________________________________

**Comment by Mottie** [comment] 2017-04-02 13:08
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Closed by Mottie** 2017-04-02 13:08 UTC
