### ISSUE TITLE
tablesorte with rowspan not work:

### ISSUE THREAD

**Issue by askovpen** [Mottie/tablesorter#806] opened 2015-01-24 18:13 UTC
tablesorte with rowspan not work:

http://jsfiddle.net/a0nghxdz/

**Comment by Mottie** [comment] 2015-01-24 22:17
Hi @askovpen!

Tablesorter does not currently support sorting `colspan` or `rowspan` settings in the tbody; duplicate of issues #110, #485 and #746.

I do plan on adding support eventually, but it will be in the tablesorter update renamed to [Abelt](https://github.com/tablesort/Abelt) - it is still a work in progress.

**Closed by Mottie** 2015-01-24 22:17 UTC

**Comment by loostro** [comment] 2015-02-22 17:52
Hi @askovpen @Mottie 

I've had a similar problem. I've resolved it useing event handlers:

```js
    $('table').bind("sortEnd updateComplete",function(e, table) {
    	$(table).find("[data-row]").each(function(idx, parent){
    		var $parent = $(parent);
    		var $rows = $(table).find('[data-parent="'+$parent.data('row')+'"]');

            // this is needed only to keep "odd"/"even" classes in sync with parent
            // uncomment only if you use zebra
    		// if ($parent.hasClass('odd')) {
    		// 	$rows.removeClass('even').addClass('odd');
    		// } else {
    		// 	$rows.removeClass('odd').addClass('even');
    		// }

            // move rows only if needed
    		if ($rows.first().prev('tr')[0] != $parent[0]) {
    			$parent.after($rows);
    		}

            // cancel hiding child rows
    		$rows.show();
    	});
    });
```

> Note: moveing many child rows may cause performance issues. In my case, my tables were not going to contain too much rows, so I did not care.

**Comment by sytolk** [comment] 2015-08-31 13:29
Thanks @loostro
